
import './css/style.css'
import { Inter, Architects_Daughter } from 'next/font/google'
import Header from '@/components/ui/header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-[#181818] tracking-tight`}>
        <div className="flex flex-col h-[80px] w-full overflow-hidden sticky z-30 top-0 ">
          <Header />
          
        </div>
        <div className="flex flex-col w-full overflow-hidden  ">
          {children}
        </div>
      </body>
    </html>
  )
}
 